### ISSUE TITLE
Cannot connect to mysql host (container)

### ISSUE THREAD

**Issue by philipkobernik** [deitch/mysql-backup#43]
Hello,

thanks for the helpful library!

I'm having an issue when running the restore command:
```
docker run -e DB_SERVER=db -e DB_PORT=3306 -e DB_USER=root -e DB_PASS=pass -e DB_RESTORE_TARGET=/backup/db_backup_20180511233943.gz -v ~/mysql_backups:/backup deitch/mysql-backup
```

'db' is the name of my mysql service defined in docker-compose.yml. when I used ```DB_SERVER=db```, I get ```ERROR 2005 (HY000): Unknown MySQL server host 'db'```

then I added port mapping so that 3306 is open on the container and on the host.

when I used ```DB_SERVER=0.0.0.0```, I get ```ERROR 2003 (HY000): Can't connect to MySQL server on '0.0.0.0' (111 "Connection refused")```

when I used ```DB_SERVER=localhost```, I get ```ERROR 2002 (HY000): Can't connect to local MySQL server through socket '/run/mysqld/mysqld.sock' (2 "No such file or directory")```

How do you usually connect to the container?

**Comment by Notifium** [comment]
Hi Philip,

I'm not sure if this helps, but here's my docker-compose for a Rancher setup:

```
version: "2"
services:

    rancher:
      container_name: rancher-server
      image: rancher/server:v1.6.17
      ports:
          - "8080:8080"
      volumes:
        - /mnt/x:/x
        - /mnt/x/data/rancher/mysql:/var/lib/mysql
      restart: unless-stopped

    backup:
        container_name: rancher-backup
        image: deitch/mysql-backup:9c5a5e0a41ce269abc3ab776feebd5576ecefc5f
        volumes:
            - /mnt/x:/x
            - /mnt/x/backups/rancher:/x/backups/rancher
            - /mnt/x/scripts/rancher/backup/prebackup:/scripts.d/pre-backup
            - /mnt/x/scripts/rancher/backup/postbackup:/scripts.d/post-backup
        environment:
         - DB_DUMP_TARGET=/x/backups/rancher/hourly
         - DB_USER=xxx
         - DB_PASS=xxx
         - DB_SERVER=rancher
         - DB_DUMP_FREQ=15
         - DB_DUMP_DEBUG=true
```

Regards,
Andy
