### ISSUE TITLE
Please provide an option to keep at most x number of backups

### ISSUE THREAD

**Issue by AndrewBedscastle** [deitch/mysql-backup#48]
Hi,
it would be nice to be able to specify a number of backups to keep, oldest backups are removed automatically.

Best regards
Andreas

**Comment by michabbb** [comment]
@AndrewBedscastle [i had the same idea](https://github.com/deitch/mysql-backup/issues/68#issuecomment-453191296) but a simple "find rm" solves that problem for most cases. 
i guess (never tested) it should also work with `/scripts.d/pre-backup` or `/scripts.d/post-backup`

**Comment by Bessonov** [comment]
Workaround for S3 users:

1. Create versioned bucket with expiration:
```
Resources:
  BackupServiceS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: backup
      VersioningConfiguration:
        Status: Enabled
      LifecycleConfiguration:
        Rules:
          # clean up old unfinished uploads
          - AbortIncompleteMultipartUpload:
              DaysAfterInitiation: 7
            Status: Enabled
          # hold removed files for 14 days
          - NoncurrentVersionExpirationInDays: 14
            Status: Enabled
```
2. Set static name for backup:

```
apiVersion: v1
kind: ConfigMap 
metadata:
  name: backup
data:
  target.sh: |
    #!/bin/bash
    echo "backup.tgz"
[...]
            volumeMounts:
            - name: backup
              mountPath: /scripts.d/target.sh
              subPath: target.sh
```

Now, backup file is overridden on every backup and old versions are away after 14 days. You can get not expired backups through console or api.
