### ISSUE TITLE
Permission denied issue

### ISSUE THREAD

**Issue by dinoperovic** [deitch/mysql-backup#60]
Hi.

I've been using your image on multiple projects and have noticed that suddenly backups stopped working. 

I started getting this errors:

```bash
mysqldump: Got error: 1045: "Access denied for user 'appuser'@'10.0.2.11' (using password: YES)" when trying to connect
```
```bash
mv: can't create '/backup/db_backup_20181023070223.gz': Permission denied
```

My `docker-compose.yml` config looks like this (truncated):

```yml
backup:
    image: deitch/mysql-backup
    restart: always
    env_file: conf/production.env
    volumes:
      - ./conf/post-backup:/scripts.d/post-backup
      - backupdata:/backup
    networks:
      - webnet
    depends_on:
      - mysql

volumes:
  backupdata:
```

with env variables:
```
DB_SERVER=mysql
DB_PASS=***
DB_NAMES=mydbname
DB_DUMP_BEGIN=2130
```

I found you made the change to run commands as non-root user here: https://github.com/deitch/mysql-backup/commit/37f78ca290b7011ee3281fa2993fd11be8ae7227

Since I've not used a specific tag on your image, it automatically upgraded to the latest version hence broke my backups (I manage around 40-50 deployments that are using your script).

Could you please help on what would be an upgrade process to support this new change, or am I better of locking in the older tag on the image?

Thanks! :)

**Comment by deitch** [comment]
Hi @dinoperovic . Interesting. First report I have had with an issue relating to non-root, but let's figure it out.

> I've not used a specific tag on your image

May I recommend tagging? I don't do `latest` (tagless) anywhere now. I have run into too many problems like this with many products. Even those that use semver versioning have that issue with `latest`. I have been sorely tempted to just remove `latest` tag entirely, but that upset too many people :-)

**Comment by deitch** [comment]
I find it interesting that it has a problem with the `backupdata` volume when running as non-root. Where is it mounted from?

In the meantime, you can just force it to run as root (override the default) by changing the compose file:

```yml
backup:
    image: deitch/mysql-backup
    restart: always
    user: "0"
    env_file: conf/production.env
    volumes:
      - ./conf/post-backup:/scripts.d/post-backup
      - backupdata:/backup
    networks:
      - webnet
    depends_on:
      - mysql
```

**Comment by dinoperovic** [comment]
Yes that's my fault not tagging, I realise now it's a bad idea using the latest tag.

This is the output for `docker inspect app_backupdata`:
```bash
[
    {
        "CreatedAt": "2018-10-23T07:41:05Z",
        "Driver": "local",
        "Labels": {
            "com.docker.stack.namespace": "app"
        },
        "Mountpoint": "/var/lib/docker/volumes/app_backupdata/_data",
        "Name": "app_backupdata",
        "Options": null,
        "Scope": "local"
    }
]
```

**Comment by dinoperovic** [comment]
Adding `user: "0"` option and re-creating the stack did fix it.

**Comment by dinoperovic** [comment]
I have had similar issue in my personal Dockerfile when using non-root users and modifying the data inside the volume. My workaround was to create the mounted directory inside the Dockerfile and give permissions to the user. 

I'm not familiar with how the `/backup` directory gets created in your script. 

This is what I did in my case:
```Dockerfile
RUN mkdir -p /backup && chown -R appuser:appuser /backup
```

**Comment by deitch** [comment]
> Adding user: "0" option and re-creating the stack did fix it.

Yep. As a general rule, I think the backup should not run as root, at least not as default. If you want to run it as root in your own context, that is your choice (hence the `docker run` and compose options), but it shouldn't default there.

> I have had similar issue in my personal Dockerfile when using non-root users and modifying the data inside the volume. My workaround was to create the mounted directory inside the Dockerfile and give permissions to the user.

The problems really become when you share volumes. If the data is entirely inside your container, then it doesn't matter (from the permissions perspective, not the security perspective, where it can matter; check out any decent video by Liz Rice) if it runs as root or not. The dir and data will be created by that user and accessed by it.

If you share a volume, then the user inside the container may be X and on the host Y, or container A may have X and container B may have Y.

Generally, in cases like this, where I _have_ to share a directory, I will try to create a volume with the right owner and share to other containers. Or, even better, avoid shared disks... but that isn't always possible. :-)

**Comment by dinoperovic** [comment]
Thanks for the explanation!

Will try to modify the permissions for the volume, even though I think using the named volumes in docker-compose always end up mounted as root, so there's not much I could do.

In that case I might fall back to forcing the root user.

Thank you. :)

**Comment by dinoperovic** [comment]
> I believe as of Docker 1.10 it respects the ownership of the first one that mounts it.

That seems to be the case running `docker-compose up -d`, my issue appears when using 
`docker stack deploy` command which is what I use on the server.

**Comment by dinoperovic** [comment]
Just as a note, testing with `docker-compose.yml`:
```yml
version: "3.6"

services:
  backup:
    image: deitch/mysql-backup
    restart: always
    volumes:
     - backupdata:/db
    environment:
     - DB_DUMP_TARGET=/db
     - DB_USER=root
     - DB_PASS=pass123
     - DB_DUMP_FREQ=60
     - DB_DUMP_BEGIN=+1
     - DB_SERVER=mysql_db
     - DB_NAMES=test_db
    networks:
      - webnet
  mysql_db:
    image: mysql
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=pass123
      - MYSQL_DATABASE=test_db
    networks:
      - webnet

networks:
  webnet:

volumes:
  backupdata:
```

Running `docker-compose up -d` works as expected.

But running the stack equivalent:
```bash
docker swarm init
docker stack deploy -c docker-compose.yml app
docker service logs -f app_backup
```
Wait for 1 min and the error will appear. This is where my issue is.
