### ISSUE TITLE
[CRON] Date problem in the periodic CRON update

### ISSUE THREAD

**Issue by bastien-7** [deitch/mysql-backup#85]
Hello, 
We have a problem when we use your docker image. Our docker-compose file is the following : 

```
version: '2'
services:
    mysql-backup:
      user: "0"
      image: deitch/mysql-backup
      environment:
       - DB_DUMP_TARGET=/backup
       - DB_USER=root
       - DB_DUMP_CRON=0 0 * * *
       - DB_SERVER=test-mysql
      volumes:
        - ./backup:/backup
      restart: always
```
The database 'test-mysql' is running in an docker image and works great.

While using this command : sudo docker-compose -f docker-compose-file.yml up we have this error :

```
WARNING: Found orphan containers (docker_test-mysql_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating docker_mysql-backup_1 ... 
Recreating docker_mysql-backup_1 ... done
Attaching to docker_mysql-backup_1
mysql-backup_1  | DB_PORT not provided, defaulting to 3306
mysql-backup_1  | Starting at Mon Feb 4 14:57:13 UTC 2019
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | date: invalid date ''
mysql-backup_1  | /functions.sh: line 244: % 7 : syntax error: operand expected (error token is "% 7 ")
mysql-backup_1  | BusyBox v1.29.3 (2019-01-24 07:45:07 UTC) multi-call binary.
mysql-backup_1  | 
mysql-backup_1  | Usage: sleep [N]...
mysql-backup_1  | 
mysql-backup_1  | Pause for a time equal to the total of the args given, where each arg can
mysql-backup_1  | have an optional suffix of (s)econds, (m)inutes, (h)ours, or (d)ays

```
We have looked at the function "wait_for_cron()"  and it worked well in our shell terminal... We expected to have a backup every day (thanks to the CRON 0 0 * * * * * parameter) but the image is in failure and it runs in a loop while constantly saving the database.
Are we doing something wrong? 
Thank you.

**Comment by deitch** [comment]
Nope, looks like you found a bug. Will get to it.

**Comment by Jarlax07** [comment]
Hello, 
Thank you for fixing this but now there is an issue with the sleep.
My docker-compose file looks like this : 
```
version: '2'
services:
    mysql-backup:
      user: "0"
      image: deitch/mysql-backup
      environment:
       - DB_DUMP_TARGET=/backup
       - DB_USER=root
       - DB_SERVER=mysql-mysql
       - DB_DUMP_CRON=43 * * * *
      volumes:
       - ./backup:/backup
      restart: always

```
And I'm getting the following errors when starting docker with : 
sudo docker-compose -f src/main/docker/backup-mysql.yml up
```
WARNING: Found orphan containers (docker_mysql-mysql_1, docker_example-db-backup_1) for this project. If you removed or renamed this service in your compose file, you can run this command with the --remove-orphans flag to clean it up.
Recreating mysql-mysql ... done
Attaching to docker_mysql-backup_1
mysql-backup_1  | DB_PORT not provided, defaulting to 3306
mysql-backup_1  | Starting at Wed Feb 6 13:42:06 UTC 2019
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134300.sql
mysql-backup_1  | sleep: invalid number '-1'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134301.sql
mysql-backup_1  | sleep: invalid number '-2'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134302.sql
mysql-backup_1  | sleep: invalid number '-3'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134303.sql
mysql-backup_1  | sleep: invalid number '-4'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134304.sql
mysql-backup_1  | sleep: invalid number '-5'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134305.sql
mysql-backup_1  | sleep: invalid number '-6'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134306.sql
mysql-backup_1  | sleep: invalid number '-7'
mysql-backup_1  | ./
mysql-backup_1  | ./backup_20190206134307.sql
mysql-backup_1  | sleep: invalid number '-8'

```

So I'm supposing that the wait_for_cron function is returning an invalid result and needs to be fixed somehow.
